apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: klusterlet
  namespace: open-cluster-management-agent
spec:
  channel: stable
  name: klusterlet
  source: operatorhubio-catalog
  sourceNamespace: olm%